on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/configure-pages@v5
      
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - name: Build
        run: |
          PREFIX=$(git rev-parse --show-toplevel | xargs basename)
          npm install
          npm run build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site/
          preview-branch: pages
          umbrella-dir: preview
