on:
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - name: Build
        run: |
          PREFIX=$(git rev-parse --show-toplevel | xargs basename)
          npm install
          npm run build
      - id: deployment
        uses: ./.github/actions/publish
        with:
          folder: _site
          branch: pages
          id: ${{ github.event.number }}
