on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/configure-pages@v5
      
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - run: |
          echo "PATH_PREFIX=${{ steps.deployment.outputs.page_url }}" >> $GITHUB_ENV
      - run: npm install && npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      - name: Deploying to pages
        uses: actions/deploy-pages@v4
